modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="moblastwords"
version="1.0.0"
displayName="Mob Last Words"
updateJSONURL=""
displayURL=""
logoFile=""
credits=""
authors="Komikan"
description='''
モブがプレイヤーによってキルされた際にランダムなメッセージをチャットに表示するMODです。
'''

[[dependencies.moblastwords]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.moblastwords]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"